/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellersSellerIdRouteImport } from './routes/sellers.$sellerId'
import { Route as ProductsIdRouteImport } from './routes/products.$id'

const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersSellerIdRoute = SellersSellerIdRouteImport.update({
  id: '/sellers/$sellerId',
  path: '/sellers/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/products/$id': typeof ProductsIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/products/$id': typeof ProductsIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/categories': typeof CategoriesRoute
  '/products/$id': typeof ProductsIdRoute
  '/sellers/$sellerId': typeof SellersSellerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/categories'
    | '/products/$id'
    | '/sellers/$sellerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/categories' | '/products/$id' | '/sellers/$sellerId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/categories'
    | '/products/$id'
    | '/sellers/$sellerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CategoriesRoute: typeof CategoriesRoute
  ProductsIdRoute: typeof ProductsIdRoute
  SellersSellerIdRoute: typeof SellersSellerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$sellerId': {
      id: '/sellers/$sellerId'
      path: '/sellers/$sellerId'
      fullPath: '/sellers/$sellerId'
      preLoaderRoute: typeof SellersSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CategoriesRoute: CategoriesRoute,
  ProductsIdRoute: ProductsIdRoute,
  SellersSellerIdRoute: SellersSellerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
